In [50]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score 
from sklearn.linear_model import LogisticRegression

In [15]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [16]:
path = "/content/seeds.txt"

In [19]:
df = pd.read_csv(path)

In [20]:
display(df)

      Area  Perimeter  Compactness  Length  Width  Asymmetry  Groove  Class
0    15.26      14.84       0.8710   5.763  3.312      2.221   5.220      1
1    14.88      14.57       0.8811   5.554  3.333      1.018   4.956      1
2    14.29      14.09       0.9050   5.291  3.337      2.699   4.825      1
3    13.84      13.94       0.8955   5.324  3.379      2.259   4.805      1
4    16.14      14.99       0.9034   5.658  3.562      1.355   5.175      1
..     ...        ...          ...     ...    ...        ...     ...    ...
205  12.19      13.20       0.8783   5.137  2.981      3.631   4.870      3
206  11.23      12.88       0.8511   5.140  2.795      4.325   5.003      3
207  13.20      13.66       0.8883   5.236  3.232      8.315   5.056      3
208  11.84      13.21       0.8521   5.175  2.836      3.598   5.044      3
209  12.30      13.34       0.8684   5.243  2.974      5.637   5.063      3

[210 rows x 8 columns]

In [21]:
df.head(10)

    Area  Perimeter  Compactness  Length  Width  Asymmetry  Groove  Class
0  15.26      14.84       0.8710   5.763  3.312      2.221   5.220      1
1  14.88      14.57       0.8811   5.554  3.333      1.018   4.956      1
2  14.29      14.09       0.9050   5.291  3.337      2.699   4.825      1
3  13.84      13.94       0.8955   5.324  3.379      2.259   4.805      1
4  16.14      14.99       0.9034   5.658  3.562      1.355   5.175      1
5  14.38      14.21       0.8951   5.386  3.312      2.462   4.956      1
6  14.69      14.49       0.8799   5.563  3.259      3.586   5.219      1
7  14.11      14.10       0.8911   5.420  3.302      2.700   5.000      1
8  16.63      15.46       0.8747   6.053  3.465      2.040   5.877      1
9  16.44      15.25       0.8880   5.884  3.505      1.969   5.533      1

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Area         210 non-null    float64
 1   Perimeter    210 non-null    float64
 2   Compactness  210 non-null    float64
 3   Length       210 non-null    float64
 4   Width        210 non-null    float64
 5   Asymmetry    210 non-null    float64
 6   Groove       210 non-null    float64
 7   Class        210 non-null    int64
dtypes: float64(7), int64(1)
memory usage: 13.2 KB

In [23]:
df.isna().sum()

Area           0
Perimeter      0
Compactness    0
Length         0
Width          0
Asymmetry      0
Groove         0
Class          0
dtype: int64

In [29]:
x = df.drop('Class', axis = 1)

In [30]:
x

      Area  Perimeter  Compactness  Length  Width  Asymmetry  Groove
0    15.26      14.84       0.8710   5.763  3.312      2.221   5.220
1    14.88      14.57       0.8811   5.554  3.333      1.018   4.956
2    14.29      14.09       0.9050   5.291  3.337      2.699   4.825
3    13.84      13.94       0.8955   5.324  3.379      2.259   4.805
4    16.14      14.99       0.9034   5.658  3.562      1.355   5.175
..     ...        ...          ...     ...    ...        ...     ...
205  12.19      13.20       0.8783   5.137  2.981      3.631   4.870
206  11.23      12.88       0.8511   5.140  2.795      4.325   5.003
207  13.20      13.66       0.8883   5.236  3.232      8.315   5.056
208  11.84      13.21       0.8521   5.175  2.836      3.598   5.044
209  12.30      13.34       0.8684   5.243  2.974      5.637   5.063

[210 rows x 7 columns]

In [32]:
y = df["Class"]

In [33]:
y

0      1
1      1
2      1
3      1
4      1
      ..
205    3
206    3
207    3
208    3
209    3
Name: Class, Length: 210, dtype: int64

In [39]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=123)

In [35]:
x_train

      Area  Perimeter  Compactness  Length  Width  Asymmetry  Groove
161  12.02      13.33       0.8503   5.350  2.810      4.271   5.308
127  17.98      15.85       0.8993   5.979  3.687      2.257   5.919
170  11.02      13.00       0.8189   5.325  2.701      6.735   5.163
165  12.10      13.15       0.8793   5.105  2.941      2.201   5.056
188  11.23      12.82       0.8594   5.089  2.821      7.524   4.957
..     ...        ...          ...     ...    ...        ...     ...
17   15.69      14.75       0.9058   5.527  3.514      1.599   5.046
98   18.17      16.26       0.8637   6.271  3.512      2.853   6.273
66   14.34      14.37       0.8726   5.630  3.190      1.313   5.150
126  18.65      16.41       0.8698   6.285  3.594      4.391   6.102
109  18.55      16.22       0.8865   6.153  3.674      1.738   5.894

[168 rows x 7 columns]

In [36]:
x_test

      Area  Perimeter  Compactness  Length  Width  Asymmetry  Groove
173  11.40      13.08       0.8375   5.136  2.763      5.588   5.089
178  11.48      13.05       0.8473   5.180  2.758      5.876   5.002
182  12.19      13.36       0.8579   5.240  2.909      4.857   5.158
132  15.38      14.90       0.8706   5.884  3.268      4.462   5.795
190  10.93      12.80       0.8390   5.046  2.717      5.398   5.045
196  12.79      13.53       0.8786   5.224  3.054      5.483   4.958
199  12.76      13.38       0.8964   5.073  3.155      2.828   4.830
171  11.55      13.10       0.8455   5.167  2.845      6.715   4.956
95   16.87      15.65       0.8648   6.139  3.463      3.696   5.967
31   15.49      14.94       0.8724   5.757  3.371      3.412   5.228
42   13.16      13.55       0.9009   5.138  3.201      2.461   4.783
180  11.41      12.95       0.8560   5.090  2.775      4.957   4.825
192  11.87      13.02       0.8795   5.132  2.953      3.597   5.132
120  20.24      16.91       0.8897   6.315  3.962      5.901   6.188
19   12.72      13.57       0.8686   5.226  3.049      4.102   4.914
72   17.26      15.73       0.8763   5.978  3.594      4.539   5.791
20   14.16      14.40       0.8584   5.658  3.129      3.072   5.176
52   14.49      14.61       0.8538   5.715  3.113      4.116   5.396
147  12.49      13.46       0.8658   5.267  2.967      4.421   5.002
167  12.15      13.45       0.8443   5.417  2.837      3.638   5.338
119  20.03      16.90       0.8811   6.493  3.857      3.063   6.320
201  12.67      13.32       0.8977   4.984  3.135      2.300   4.745
4    16.14      14.99       0.9034   5.658  3.562      1.355   5.175
108  19.94      16.92       0.8752   6.675  3.763      3.252   6.550
158  11.75      13.52       0.8082   5.444  2.678      4.378   5.310
21   14.11      14.26       0.8722   5.520  3.168      2.688   5.219
91   18.76      16.20       0.8984   6.172  3.796      3.120   6.053
159  11.49      13.22       0.8263   5.304  2.695      5.388   5.310
137  15.57      15.15       0.8527   5.920  3.231      2.640   5.879
195  12.80      13.47       0.8860   5.160  3.126      4.873   4.914
198  12.62      13.67       0.8481   5.410  2.911      3.306   5.231
53   14.33      14.28       0.8831   5.504  3.199      3.328   5.224
181  12.46      13.41       0.8706   5.236  3.017      4.987   5.147
163  12.55      13.57       0.8558   5.333  2.968      4.419   5.176
185  11.56      13.31       0.8198   5.363  2.683      4.062   5.182
162  12.05      13.41       0.8416   5.267  2.847      4.988   5.046
10   15.26      14.85       0.8696   5.714  3.242      4.543   5.314
71   16.84      15.67       0.8623   5.998  3.484      4.675   5.877
80   16.53      15.34       0.8823   5.875  3.467      5.532   5.880
26   13.02      13.76       0.8641   5.395  3.026      3.373   4.825
11   14.03      14.16       0.8796   5.438  3.201      1.717   5.001
194  12.11      13.27       0.8639   5.236  2.975      4.132   5.012

In [37]:
y_train

161    3
127    2
170    3
165    3
188    3
      ..
17     1
98     2
66     1
126    2
109    2
Name: Class, Length: 168, dtype: int64

In [40]:
y_test

173    3
178    3
182    3
132    2
190    3
196    3
199    3
171    3
95     2
31     1
42     1
180    3
192    3
120    2
19     1
72     2
20     1
52     1
147    3
167    3
119    2
201    3
4      1
108    2
158    3
21     1
91     2
159    3
137    2
195    3
198    3
53     1
181    3
163    3
185    3
162    3
10     1
71     2
80     2
26     1
11     1
194    3
Name: Class, dtype: int64

In [41]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((168, 7), (42, 7), (168,), (42,))

In [56]:
log_model = LogisticRegression(solver='lbfgs', max_iter=1000)
#lr = LogisticRegression()
log_model.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [59]:
y_predict = log_model.predict(x_test)

In [60]:
print("\n Accuracy: {}".format(accuracy_score(y_test, y_predict) ))

 Accuracy: 0.9047619047619048